apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftp-server
    protocol: TCP
    port: 21
    nodePort: 21
  - name: ftp-data
    protocol: TCP
    port: 20
    nodePort: 20
  - name: ftp-pasv1
    protocol: TCP
    port: 30032
    nodePort: 30032
  - name: ftp-pasv2
    protocol: TCP
    port: 30033
    nodePort: 30033
  - name: ftp-pasv3
    protocol: TCP
    port: 30034
    nodePort: 30034

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: custom/ftps
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ./liveness.sh
            initialDelaySeconds: 20
            periodSeconds: 20
        ports:
        - name: ftp-server
          containerPort: 21
        - name: ftp-data
          containerPort: 20
        - name: ftp-pasv1
          containerPort: 30032
        - name: ftp-pasv2
          containerPort: 30033
        - name: ftp-pasv3
          containerPort: 30034
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home/gboucett
      volumes:
        - name: ftps-persistent-storage
          persistentVolumeClaim:
              claimName: ftps-pv-claim
