apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    nodePort: 5050
    protocol: TCP
    name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: custom/wordpress
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - ./liveness.sh
            initialDelaySeconds: 20
            periodSeconds: 20
        ports:
        - name: http
          containerPort: 5050
